In [5]:
import pandas as pd

In [7]:
my_data = pd.read_csv("C:/Users/sruja/Downloads/Dataset/website_wata.csv")

In [9]:
my_data = my_data.drop_duplicates()
my_data

,Page Views,Session Duration,Bounce Rate,Traffic Source,Time on Page,Previous Visits,Conversion Rate
0,5,11.051381,0.230652,Organic,3.890460,3,1.0
1,4,3.429316,0.391001,Social,8.478174,0,1.0
2,4,1.621052,0.397986,Organic,9.636170,2,1.0
3,5,3.629279,0.180458,Organic,2.071925,3,1.0
4,5,4.235843,0.291541,Paid,1.960654,5,1.0
...,...,...,...,...,...,...,...
1995,1,2.724513,0.207187,Referral,1.324206,2,1.0
1996,3,0.392856,0.095559,Organic,3.824416,1,1.0
1997,4,9.899823,0.446622,Organic,1.288675,1,1.0
1998,3,0.393319,0.278340,Paid,5.037584,2,1.0
1999,3,0.882638,0.338026,Direct,5.186908,3,1.0

In [11]:
# Check for Missing Values
print("Missing Values in Each Column:")
print(my_data.isnull().sum())

Missing Values in Each Column:
Page Views          0
Session Duration    0
Bounce Rate         0
Traffic Source      0
Time on Page        0
Previous Visits     0
Conversion Rate     0
dtype: int64

In [14]:
# Our dataset doesnot have any missing values. But lets assume it has some missing values.
# In that case we need to replace missing values with mean of specific column.

In [13]:
for column in my_data.select_dtypes(include=['number']).columns:  # Only process numeric columns
    if my_data[column].isnull().sum() > 0:  # Check if the column has missing values
        my_data[column] = my_data[column].fillna(my_data[column].mean())

In [15]:
my_data

,Page Views,Session Duration,Bounce Rate,Traffic Source,Time on Page,Previous Visits,Conversion Rate
0,5,11.051381,0.230652,Organic,3.890460,3,1.0
1,4,3.429316,0.391001,Social,8.478174,0,1.0
2,4,1.621052,0.397986,Organic,9.636170,2,1.0
3,5,3.629279,0.180458,Organic,2.071925,3,1.0
4,5,4.235843,0.291541,Paid,1.960654,5,1.0
...,...,...,...,...,...,...,...
1995,1,2.724513,0.207187,Referral,1.324206,2,1.0
1996,3,0.392856,0.095559,Organic,3.824416,1,1.0
1997,4,9.899823,0.446622,Organic,1.288675,1,1.0
1998,3,0.393319,0.278340,Paid,5.037584,2,1.0
1999,3,0.882638,0.338026,Direct,5.186908,3,1.0

In [17]:
#Standardize the url, if exist anywher in our dataset
if 'url' in my_data.columns:
    my_data['url'] = my_data['url'].str.lower()
else:
    print("Column 'url' does not exist in the dataset.")

Column 'url' does not exist in the dataset.

In [19]:
# Time spent per page: Average time spent per page view
my_data['Time Spent Per Page'] = my_data['Time on Page'] / my_data['Page Views']

In [21]:
# Session Duration Per Visit: Total session duration divided by previous visits
# Adding 1 to avoid division by zero if there are no previous visits
my_data['Session Duration Per Visit'] = my_data['Session Duration'] / (my_data['Previous Visits'] + 1)

In [23]:
# Categorize traffic sources into a numerical values
traffic_mapping = {'Direct': 1, 'Referral': 2, 'Social Media': 3, 'Organic': 4}
my_data['Traffic Source Code'] = my_data['Traffic Source'].map(traffic_mapping)

In [25]:
# To give an insight into how long users are staying per page.
my_data['Session Length to Page Views Ratio'] = my_data['Session Duration'] / my_data['Page Views']

In [42]:
my_data

,Page Views,Session Duration,Bounce Rate,Traffic Source,Time on Page,Previous Visits,Conversion Rate,Time Spent Per Page,Session Duration Per Visit,Traffic Source Code,Session Length to Page Views Ratio
0,5,11.051381,0.230652,Organic,3.890460,3,1.0,0.778092,2.762845,4.0,2.210276
1,4,3.429316,0.391001,Social,8.478174,0,1.0,2.119544,3.429316,NaN,0.857329
2,4,1.621052,0.397986,Organic,9.636170,2,1.0,2.409042,0.540351,4.0,0.405263
3,5,3.629279,0.180458,Organic,2.071925,3,1.0,0.414385,0.907320,4.0,0.725856
4,5,4.235843,0.291541,Paid,1.960654,5,1.0,0.392131,0.705974,NaN,0.847169
...,...,...,...,...,...,...,...,...,...,...,...
1995,1,2.724513,0.207187,Referral,1.324206,2,1.0,1.324206,0.908171,2.0,2.724513
1996,3,0.392856,0.095559,Organic,3.824416,1,1.0,1.274805,0.196428,4.0,0.130952
1997,4,9.899823,0.446622,Organic,1.288675,1,1.0,0.322169,4.949912,4.0,2.474956
1998,3,0.393319,0.278340,Paid,5.037584,2,1.0,1.679195,0.131106,NaN,0.131106
1999,3,0.882638,0.338026,Direct,5.186908,3,1.0,1.728969,0.220659,1.0,0.294213

In [27]:
# Identifying the top pages based on page views (this assumes each row represents a page)
top_pages = my_data['Page Views'].value_counts().head(5)
print(f"Top pages based on traffic:\n{top_pages}")

Top pages based on traffic:
Page Views
5    354
4    354
6    296
3    281
7    211
Name: count, dtype: int64

In [29]:
# Identifying low-traffic pages (pages with fewer views)
low_traffic_pages = my_data['Page Views'].value_counts().tail(5)
print(f"Low-traffic pages:\n{low_traffic_pages}")

Low-traffic pages:
Page Views
11    15
0     14
12     3
13     2
14     1
Name: count, dtype: int64

In [31]:
# Flag frequent visitors (Previous Visits > 3)
my_data['Frequent Visitor'] = my_data['Previous Visits'] > 3
print(f"Frequent Visitors:\n{my_data[['Previous Visits', 'Frequent Visitor']]}")

Frequent Visitors:
      Previous Visits  Frequent Visitor
0                   3             False
1                   0             False
2                   2             False
3                   3             False
4                   5              True
...               ...               ...
1995                2             False
1996                1             False
1997                1             False
1998                2             False
1999                3             False

[2000 rows x 2 columns]

In [33]:
# Flag first-time users (Previous Visits = 0)
my_data['First-time User'] = my_data['Previous Visits'] == 0
print(f"First-time Users:\n{my_data[['Previous Visits', 'First-time User']]}")

First-time Users:
      Previous Visits  First-time User
0                   3            False
1                   0             True
2                   2            False
3                   3            False
4                   5            False
...               ...              ...
1995                2            False
1996                1            False
1997                1            False
1998                2            False
1999                3            False

[2000 rows x 2 columns]

In [35]:
# Flag high converting users (Conversion Rate > 0.9)
my_data['High Converting User'] = my_data['Conversion Rate'] > 0.9
print(f"High Converting Users:\n{my_data[['Conversion Rate', 'High Converting User']]}")

High Converting Users:
      Conversion Rate  High Converting User
0                 1.0                  True
1                 1.0                  True
2                 1.0                  True
3                 1.0                  True
4                 1.0                  True
...               ...                   ...
1995              1.0                  True
1996              1.0                  True
1997              1.0                  True
1998              1.0                  True
1999              1.0                  True

[2000 rows x 2 columns]

In [37]:
my_data

,Page Views,Session Duration,Bounce Rate,Traffic Source,Time on Page,Previous Visits,Conversion Rate,Time Spent Per Page,Session Duration Per Visit,Traffic Source Code,Session Length to Page Views Ratio,Frequent Visitor,First-time User,High Converting User
0,5,11.051381,0.230652,Organic,3.890460,3,1.0,0.778092,2.762845,4.0,2.210276,False,False,True
1,4,3.429316,0.391001,Social,8.478174,0,1.0,2.119544,3.429316,NaN,0.857329,False,True,True
2,4,1.621052,0.397986,Organic,9.636170,2,1.0,2.409042,0.540351,4.0,0.405263,False,False,True
3,5,3.629279,0.180458,Organic,2.071925,3,1.0,0.414385,0.907320,4.0,0.725856,False,False,True
4,5,4.235843,0.291541,Paid,1.960654,5,1.0,0.392131,0.705974,NaN,0.847169,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1,2.724513,0.207187,Referral,1.324206,2,1.0,1.324206,0.908171,2.0,2.724513,False,False,True
1996,3,0.392856,0.095559,Organic,3.824416,1,1.0,1.274805,0.196428,4.0,0.130952,False,False,True
1997,4,9.899823,0.446622,Organic,1.288675,1,1.0,0.322169,4.949912,4.0,2.474956,False,False,True
1998,3,0.393319,0.278340,Paid,5.037584,2,1.0,1.679195,0.131106,NaN,0.131106,False,False,True
1999,3,0.882638,0.338026,Direct,5.186908,3,1.0,1.728969,0.220659,1.0,0.294213,False,False,True

In [39]:
# Export the final dataset to an CSV file
my_data.to_csv('FinalWebsiteDataset.csv', index=True)
# Export the final dataset to an CSV file in to your local folder
my_data.to_csv('C:/Users/sruja/Downloads/Dataset/FinalWebsiteDataset.csv', index=True)